### ISSUE TITLE
integrating monaco-yaml 

### ISSUE THREAD

**Issue by sdementen** [giorgi94/django-editor-widgets#1]
hello,

Is it possible to integrate the monaco-yaml (https://github.com/pengx17/monaco-yaml) plugin to allow yaml validation in the monaco editor ?
I am not familiar with js/yarn/etc... so I have difficulties to estimate the complexity for the integration (while avoiding requiring user of the django-editor-widgets to add extra dependencies)

**Comment by giorgi94** [comment]
Hi,

If I understand correctly, you want monaco editor with yaml syntax. I wrote this package, so that provides only essential features to have custom web editor in django admin. I don't really use yaml syntax, but I can look at the plugin.

**Comment by sdementen** [comment]
Yes indeed. The key features for me are syntax highlighting and schema validation/autocompletion (via JSON schema, also used for YAML validation)

**Comment by giorgi94** [comment]
I looked at the monaco-yaml. It requires yaml-language-server to work, so I am not able to add this feature to my package, since it needs 3rd party services. But you can easly costumize javascript, since config for editor is written in javascript (so you can use docs).
