### ISSUE TITLE
staticfiles issue with djangoeditorwidgets\static\tinymce\skins\ui\oxide-dark\tinymce-mobile.woff

### ISSUE THREAD

**Issue by sdementen** [giorgi94/django-editor-widgets#2]
I wonder if the file `tinymce-mobile.woff` should not be in a `fonts` subfolder in `djangoeditorwidgets/static/tinymce/skins/ui/oxide-dark`
https://github.com/giorgi94/django-editor-widgets/tree/master/djangoeditorwidgets/static/tinymce/skins/ui/oxide-dark
as collectstatic complains
```
The CSS file 'tinymce/skins/ui/oxide-dark/skin.mobile.min.css' references a file which could not be found:
  tinymce/skins/ui/oxide-dark/fonts/tinymce-mobile.woff
```

**Comment by sdementen** [comment]
I confirm that moving the file `tinymce-mobile.woff` to a subfolder `fonts` fixes the collectstatic error

**Comment by giorgi94** [comment]
Are you using tinymce 4 or 5, since now it is on version 5, and I don't have any problem with collectstatic?

**Comment by sdementen** [comment]
I do not think I have installed tinymce separately. I just did a "pip install" of your DEW package.
Aren't these files bundled within your package?
But I may misunderstand your question...

**Comment by giorgi94** [comment]
In project are bundled files from there github pages and these files can be easy replaced or added some plugins, since config is written directly is js files.

I updated package v3.0, made some modifications and added languages to monaco (syntax highlighting).
